<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2058" started-at="2016-06-29T10:58:24Z" finished-at="2016-06-29T10:58:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2058" started-at="2016-06-29T10:58:24Z" finished-at="2016-06-29T10:58:26Z">
      <class name="Topic9_Timeout_Testng.Example1_Timeout">
        <test-method status="FAIL" signature="testcase1()[pri:0, instance:Topic9_Timeout_Testng.Example1_Timeout@1d4c4b7]" name="testcase1" duration-ms="2039" started-at="2016-06-29T16:28:24Z" finished-at="2016-06-29T16:28:26Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method org.testng.internal.TestNGMethod.testcase1() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testcase1() didn't finish within the time-out 2000
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- Topic9_Timeout_Testng.Example1_Timeout -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
